name: Periodic Health Check

on:
  schedule:
    - cron: '0 8,18 * * *'
    # runs on 8:00am and 6:00pm everyday

jobs:
  periodic_health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          # Check the following URLs one by one sequentially
          url: https://am-thedev-pokedex.herokuapp.com/
          # Follow redirects, or just report success on 3xx status codes
          follow-redirect: no # Optional, defaults to "no"
          # Fail this action after this many failed attempts
          max-attempts: 3 # Optional, defaults to 1
          # Delay between retries
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
          # Retry all errors, including 404. This option might trigger curl upgrade.
          retry-all: no # Optional, defaults to "no"
          # The action will fail if any of the URLs reports either 4xx or 5xx status codes.